modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="skycustom"
version="1.0.0"
displayName="skycustom"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Elias, MCreator"

[[dependencies.skycustom]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




